kind: Service
apiVersion: v1
metadata:
  name: demowebapp
spec:
  selector:
    app: demowebapp
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demowebapp
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: demowebapp
        tier: frontend
        track: stable
    spec:
      containers:
        - name: demowebapp
          image: "yogurtthecat.azurecr.io/demo-webapp"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: acr