apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demowebapp
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5  
  template:
    metadata:
      labels:
        app: demowebapp
        tier: frontend
        track: stable
    spec:
      containers:
        - name: demowebapp
          image: "yogurtthecat.azurecr.io/demo-webapp:v2"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: acr